# H11 - Prod

Hanna Gröndahl

## Järjestelmätiedot

- Rauta: Dell Latitude 7290
- Raudan OS: Windows 10 Pro (10.0.19045)
- Hypervisor: Oracle VM Virtual Box 7.0.6
- Virtuaalikoneen OS: Debian GNU/Linux 11
- Kernel: Linux 5.10.0-20-amd64

## a) Tee Djangon tuotantoasennus

Aloitin harjoituksen 9.55.

Päivitin paketit `sudo apt-get update`, jotta asennettavat paketit ovat ajantasaisia. Asensin Apache 2 -palvelimen `sudo apt-get install -y apache2`. Käynnistin palvelimen `sudo systemctl start apache2` ja testasin palvelimen toiminnan `curl localhost`. Sain tulostukseksi Apachen oletusetusivun. Vaihdoin sen hillitymmäksi komennolla `echo "Here I remain"|sudo tee /var/www/html/index.html`. Käynnistin Apachen uudelleen `sudo systemctl start apache2` ja kokeilin curlia uudestaan. Nyt etusivulla luki vain tuo Here I remain.

![a2asennus](https://user-images.githubusercontent.com/122886984/222399126-77158b9c-341a-4a6e-9d48-433f205bca67.png)

Aloitin staattisten sivujen luomisen tekemällä käyttäjälle wsgi-hakemiston. WSGI toimii välikätenä käyttäjän, palvelimen ja ohjelmien välillä niin, että eri Python-ohjelmien käyttäminen web-palvelussa on sujuvaa.

	[10:18:46] hanna@testarossa2:~$ pwd
	/home/hanna
	[10:18:48] hanna@testarossa2:~$ mkdir -p publicwsgi/hannapp/static/
	[10:19:19] hanna@testarossa2:~$ echo "Kaiken takana on staattinen sivu"|tee publicwsgi/hannapp/static/index.html
	Kaiken takana on staattinen sivu

Päivitin tämän staattisen sivun web-palvelimeni määrittelyihin luomalla uuden määrittelytiedoston newest.conf `sudoedit /etc/apache2/sites-available/newest.conf`. Määrittely lessillä luettuna:

![maaritys](https://user-images.githubusercontent.com/122886984/222399161-9ecc37da-99d3-4b3e-b171-3ba7dae5fb81.png)

Tarkistin voimassaolevan määrityksen cd /etc/apache2/sites-enabled. Otin uuden määrittelyn käyttöön `sudo a2ensite newest.conf` ja otin vanhan määrittelyn pois käytöstä `sudo a2dissite 000-default.conf`. Tarkistin määritykset `/sbin/apache2ctl configtest`, ja se antoi oletetun AH005558-virheilmoituksen siitä, ettei palvelimella ole julkista nimeä. Syntaksi oli OK. Otin muutokset käyttöön käynnistämällä Apachen uudelleen `sudo systemctl restart apache2`. Tarkistin muutosten voimaantulon vielä `curl localhost/static/` ja sieltä tuli tulostus, joka osoitti määritysten onnistuneen:

![curlstatic](https://user-images.githubusercontent.com/122886984/222399215-081c166e-4fed-469d-96ec-c023cf53771e.png)

Apache2 toimii, joten on aika siirtyä Djangon asentamiseen. Virtualenv on jo asennettuna, joten siirryin /home/hanna/publicwsgi-hakemistoon luomaan virtuaaliympäristön Pythonin ajamiseksi. Komennolla `virtualenv -p python3 --system-site-packages env` loin Python3:a käyttävän virtuaaliympäristön, joka käyttää myös järjestelmään asennettuja apt-paketteja. Käynnistin virtuaaliympäristön publicwsgi-hakemistossa `source env/bin/activate`. Komentokehotteen alkuun tuli (env) ilmaisemaan, että työskentelen nyt virtuaaliympäristössä. Tarkistin Pythonin pakettiasennusohjelman pip:n sijainnin `which pip` -komennolla. 

	[10:43:01] (env) hanna@testarossa2:~/publicwsgi$ which pip
	/home/hanna/publicwsgi/env/bin/pip

Tuloste osoittaa, että pip sijaitsee virtuaaliympäristössä. Asensin Djangon luomalla requirements.txt-tiedoston, johon määritin asennettavaksi ohjelmaksi "django". Tekstitiedoston käyttäminen on turvallisuusmekanismi, jonka avulla voi olla varmempi siitä, että asentaa juuri sen ohjelman, jonka tarkoitti asentaa. 

![reqdjanjo](https://user-images.githubusercontent.com/122886984/222399233-9f786d3e-06a2-4200-9c7e-f697c7d6c5e5.png)

Tarkistin vielä komennolla `django-admin --version`, että olin asentanut uusimman version. Sain tulostukseksi 4.1.7, joka kuulostaa hyvältä, sillä se on 4+ versio. Aloitin uuden Django-projektin komennolla `django-admin startproject hannapp`. Avasin toisen terminaalin, johon avasin Apache2:n määrittelytiedoston `sudoedit /etc/apache2/sites-available/newest.conf`. Kopioin TeroKarvinen.comin määrittelyt, ja muokkasin omat hakemistoni ja käyttäjän määrittelytiedostoon.

![uudetmaarittelyt](https://user-images.githubusercontent.com/122886984/222399257-945984c3-14fa-490e-944e-1399ca0d7726.png)

Loin rajoitetuin oikeuksin varustetun nampatti-käyttäjän Django-komentojen suorittajaksi. Asensin Apachen WSGI-osan, jotta se osaa tulkita WSGI-komentoja. Tarkistin syntaksin `/sbin/apache2ctl configtest`. Sain virheilmoituksen:

	  apache2: Syntax error on line 225 of /etc/apache2/apache2.conf: Syntax error on line 31 of /etc/apache2/sites-enabled/newest.conf: </VirtualHost> without     matching <VirtualHost> section
    Action 'configtest' failed.
    The Apache error log may have more information.

Määrittelytiedostossa oli </VirtualHost> tuplana omien copy-pastettelujeni seurauksena, joten poistin niistä toisen, jotta määrittely vastasi mallia. Nyt configtest meni läpi. Käynnistin Apachen uudelleen `sudo systemctl restart apache2`. Katsoin otsikkotiedot curlilla `curl -s localhost|grep title`. Tulosteena oli: 

	<title>500 Internal Server Error</title>

Eli ei se aivan toiminut. Kokeilin selaimella staattisen sivun toiminnan, ja se kyllä toimi. `sudo systemctl status apache2` näytti, että serveri on aktiivinen. 

![ctlserver](https://user-images.githubusercontent.com/122886984/222399557-b818064d-ca08-46cc-a87a-405904e7c213.png)

Apache2:n error.login perusteella wsgi:ssä on jotain häiriötä.

	[Thu Mar 02 11:55:55.154663 2023] [wsgi:error] [pid 4945:tid 140336540346112] [remote ::1:38740]   File "/home/hanna/publicwsgi/env/lib/python3.9/site-packages/django/conf/__init__.py", line 190, in __init__
    [Thu Mar 02 11:55:55.154668 2023] [wsgi:error] [pid 4945:tid 140336540346112] [remote ::1:38740]     mod = importlib.import_module(self.SETTINGS_MODULE)
    [Thu Mar 02 11:55:55.154679 2023] [wsgi:error] [pid 4945:tid 140336540346112] [remote ::1:38740]   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    [Thu Mar 02 11:55:55.154684 2023] [wsgi:error] [pid 4945:tid 140336540346112] [remote ::1:38740]     return _bootstrap._gcd_import(name[level:], package, level)
    [Thu Mar 02 11:55:55.154694 2023] [wsgi:error] [pid 4945:tid 140336540346112] [remote ::1:38740]   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
    [Thu Mar 02 11:55:55.154705 2023] [wsgi:error] [pid 4945:tid 140336540346112] [remote ::1:38740]   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
    [Thu Mar 02 11:55:55.154730 2023] [wsgi:error] [pid 4945:tid 140336540346112] [remote ::1:38740]   File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
    [Thu Mar 02 11:55:55.154754 2023] [wsgi:error] [pid 4945:tid 140336540346112] [remote ::1:38740] ModuleNotFoundError: No module named 'hannapp.settings'

Epäilen, että virhe saattaa olla tiedostopoluissa, tai sitten tuon Wsgi:n asennus meni jotenkin pieleen. Yritin googlata ongelmaa, mutta en saanut sitä tässä vaiheessa ratkaistua. Palaan asiaan vielä ennen luentoa, ja päivitän tähän tiedostoon jos saan tämän ratkaistua.

Harjoituksen tekeminen tältä erää päättyy 12.10.

### Debuggaus jatkuu - ja onnistuu

Tästä eteenpäin suppeampi raportointi, koska tämä on myöhempää lisäystä. 

17:45 Palasin töiden jälkeen katsomaan mikä tässä olikaan pielessä, ja osoittautui, että vika on siinä, että tiedostorakenteesta tuli jokseekin omalaatuinen. Noita hannapp-kansioita on tosiaan jostain syystä kolme sisäkkäin, minkä takia en nyt äkkiä saa staattista ja dynaamista sivua toimimaan yhtä aikaa. Lisäämällä TDIRin määritelmään yhtä alemman hannapp-hakemiston Django alkaa pyörimään localhostissa, mutta staattinen sivu ei löydy. Yksi vaihtoehto on ottaa muutama askel taaksepäin, mutta koitan korjata, koska korjaaminen voi olla parempi kuin uuden tekeminen.

17:50 Korjasin sen hakemistorakenteen ja muokkasin newest.confin vastaamaan sitä.

![kuva](https://user-images.githubusercontent.com/122886984/222480036-f30dea52-d7bc-4709-a862-2e35620ec722.png)

18:44 Muokkasin settings.py-tiedostosta debugin pois päältä, lisäsin localhostin Allowed hostiin. Kosketin wsgi:tä, käynnistin Apachen uudelleen. Päivitin selaimessa localhostin, odotetusti tuli Not found. Kokeilin myös satunnaista localhost/moro666 urlia eikä debug kurkistanut sieltäkään. Muotoilematon localhost/admin näkyi. Kirjautuminen ei kuitenkaan toiminut, sieltä tuli Server error (500). Tein migraation, loin uuden superuserin. Palaan tähän taas myöhemmin.

Muokkasin settings.py:tä laittamalla alkuun import os:in ja lisäämällä static rootin. Login-näkymä sai onnistuneesti väriä. Tuota Server error -ongelmaa en nyt saanut ratkottua, vähän pelkään että ongelma juontaa tuohon aikaisempaan huonoon hakemistorakenteeseen.

3.3. 14.02 Laitoin Debugin päälle:

![kuva](https://user-images.githubusercontent.com/122886984/222715451-3821f337-7b70-4ed1-8ab9-636d2d092fbd.png)

14:19 Virheilmoituksen perusteella päädyin vaihtamaan newest.confissa hallinoivaksi käyttäjäksi rajoitetun käyttäjän sijaan sudo-käyttäjäni. Nyt kaikki toimii niin kuin pitääkin. Fiuh.

## Lähteet

- Karvinen, T. s.a. Deploy Django 4 - Production Install. https://terokarvinen.com/2022/deploy-django/. Luettu 24.2.2023.
- Karvinen, T. 2023. Linux-palvelimet-kurssin luento 28.2.2023.
