## H12 - Vianselvitys

Hanna Gröndahl

## Järjestelmätiedot

- Rauta: Dell Latitude 7290
- Raudan OS: Windows 10 Pro (10.0.19045)
- Hypervisor: Oracle VM Virtual Box 7.0.6
- Virtuaalikoneen OS: Debian GNU/Linux 11
- Kernel: Linux 5.10.0-20-amd64

## x) Aluksi

Tämän tehtävän tarkoituksena on aiheuttaa vikoja Djangon tuotantoasennukseen, osoittaa vikojen ilmeneminen ja korjata ne. Tehtävän tekeminen alkaa 23.30. Tehtävän alustana toimii [viime harjoituksessa](https://github.com/hannagrn/linux-pal/blob/main/h11.md) käyttämäni virtuaalikone, johon Django on otettu tuotantoon onnistuneesti. Tehtävän teko alkaa 0.00. 

## a) Kirjoitusvirhe Python-tiedostossa

Laitoin virtualenvin päälle komennolla `source env/bin/activate`. Menin kansioon /publicwsgi/hannapp/hannapp ja avasin sieltä microlla settings.py:n. Tein sinne pienen kirjoitusvirheen ja kommentoin oikean komennon talteen. Oletin, että admin-sivu ei näytä tyylitellyltä, jos tämän muuttaa.

![kuva](https://user-images.githubusercontent.com/122886984/222988992-a700f889-83a7-429f-98ad-18e57541f7a5.png)

Koitin ottaa muutoksen käyttöön tekemällä migraatiot, mutta heti `./manage.py makemigrations`-komennon ajaminen antoi virheilmoituksen virheellisestä syntaksista settings.py-tiedostossa. 

![kuva](https://user-images.githubusercontent.com/122886984/222989149-92896044-a738-4a85-af47-0f1cd3a48ad9.png)

Menin takaisin settings.py:hyn, poistin virheellisen komennon ja otin risuaidan oikean komennon edestä pois. Tallensin muutokset, ja nyt `./manage.py makemigrations` sai tulosteeksi "No changes detected", eli lähtötilanteeseen verrattuna tilanne oli sama, sillä aiheuttamaani virhettä ei otettu tuotannossa käyttöön. 

## b) Django-projektikansio väärässä paikassa

Siirsin hannapp-projektikansion publicwsgi:stä wrongway-kansioon `mv /home/hanna/publicwsgi/hannapp/ /home/hanna/wrongway`. Tarkastin, että komento toimi toivotusti tarkastelemalla hakemistojen sisältöjä.

![kuva](https://user-images.githubusercontent.com/122886984/222990317-3b90caad-542a-49a4-bd9e-4cdc4f0c0a3e.png)

Lähtötilanteessa curlaamalla localhostin sai vastaukseksi Not found -virheilmoituksen, mutta nyt otsikkotietojen curlaus `curl -s localhost | grep title` tarjosi 403 Forbidden -virhettä. Sama vastaus tuli myös localhost/admin:sta. `sudo systemctl status apache2` näytti Apache-palvelimen pyörivän iloisesti:

![kuva](https://user-images.githubusercontent.com/122886984/222990650-eb744a26-4ed2-4c28-8309-363336902fce.png)

Apachen error.log näytti kuitenkin, että palvelinmäärittelyt estävät asiakkaan pyynnön.

    [Mon Mar 06 00:55:15.603263 2023] [authz_core:error] [pid 2851:tid 140232437151488] [client 127.0.0.1:53798] AH01630: client denied by  server configuration: /home/hanna/publicwsgi/hannapp
    [Mon Mar 06 00:55:15.691246 2023] [authz_core:error] [pid 2851:tid 140232359933696] [client 127.0.0.1:53798] AH01630: client denied by server configuration: /home/hanna/publicwsgi/hannapp, referer: http://localhost/

Conf-tiedostossahan tosiaan projektikansion paikaksi on määritelty publicwsgi eikä wrongway. Korjasin virheen palauttamalla tiedostopolun sellaiseksi, kuin se on määritelty komennolla `mv wrongway /home/hanna/publicwsgi/hannapp`. Päivitin selaimessa localhostin tarkistaakseni onnistuiko korjaus. Ensin sain Internal server error -virheilmoituksen, joka ei vastannut lähtötilannetta. Käynnistin Apachen uudelleen komennolla `sudo systemctl restart apache2`. Nyt localhostiin tuli odotettu Not found -virheilmoitus, ja myös admin-sivu toimi jälleen.

## c) Projektikansiolla väärät oikeudet

Otin projektihakemistolta oikeudet komennolla `chmod ugo-rwx hannapp` publicwsgi/hannapp-hakemistossa. Chmod tarkoittaa käyttöoikeuksien hallintaa, ugo rajaa sen, ketä komento koskee ja -rwx tarkoittaa mitkä oikeudet poistetaan. Komento tarkoittaa siis sitä, että hannapp-hakemistossa kukaan ei saa tehdä mitään.  Muutos näkyi selaimen päivittämällä heti localhostissa:

![kuva](https://user-images.githubusercontent.com/122886984/222991497-9564c8ab-27e6-4402-8b21-52ddc2281c59.png)

Tämä siis Not found -virheilmoituksen sijasta. Muutos kirjoitti Apachen error.logiin seuraavasti:

    [Mon Mar 06 01:12:45.439870 2023] [core:error] [pid 2995:tid 140045109417728] (13)Permission denied: [client 127.0.0.1:34264] AH00035: access to /admin/ denied (filesystem path '/home/hanna/publicwsgi/hannapp/hannapp/wsgi.py') because search permissions are missing on a component of the path
    [Mon Mar 06 01:12:45.665241 2023] [core:error] [pid 2995:tid 140045101025024] (13)Permission denied: [client 127.0.0.1:34264] AH00035: access to /favicon.ico denied (filesystem path '/home/hanna/publicwsgi/hannapp/hannapp/wsgi.py') because search permissions are missing on a component of the path, referer: http://localhost/admin/
    [Mon Mar 06 01:14:08.208437 2023] [core:error] [pid 2995:tid 140045075846912] (13)Permission denied: [client 127.0.0.1:42468] AH00035: access to / denied (filesystem path '/home/hanna/publicwsgi/hannapp/hannapp/wsgi.py') because search permissions are missing on a component of the path
   
Pääsy resursseihin estettiin, koska wsgi.py:tä ei voi suorittaa. Palautin oikeuksia ensin vähemmän komennolla `u+rwx`, mutta se ei riittänyt, koska selain näytti localhost/adminissa 403 Forbidden -virheilmoitusta. Korjasin oikeudet kohdalleen antamalla lisää oikeuksia `ugo+rwx`. Pohdin, että en ole aivan varma siitä, oliko kaikilla ryhmillä tosiaan rwx-oikeudet alkutilanteessa, koska ne kuulostavat aika laajoilta oikeuksilta. Nyt localhostissa oli tuttu Not found ja admin näkyi selaimessa toivotulla tavalla.

![kuva](https://user-images.githubusercontent.com/122886984/222992480-e37216d7-3805-46ff-b5a0-91858a354541.png)

01.35 tehtävän tekeminen päättyi tältä päivältä.

## d) Kirjoitusvirhe Apachen asetustiedostossa 

Jatkuu 10.30.

Siirryin muokkaamaan käytössä olevaa asetustiedostoa `micro /etc/apache2/sites-available/newest.conf`. Muokkasin alun polkumäärittelyihin pienen virheen lisäämällä wsgi.py:n loppuun vielä yhden kauttaviivan. Kommentoin oikean polun talteen. 

![kuva](https://user-images.githubusercontent.com/122886984/223060290-c9c302e3-51a4-4474-b299-e76d7276b0df.png)

Tallennettuani muutokset päivitin localhost/admin/ selaimessa, ja kaikki toimi. Tarkistin confin syntaksin `/sbin/apache2 configtest`. Sain varoituksen syntaksivirheestä rivillä 2. Error.logissa ei näkynyt vielä mitään uutta viime yön jälkeen.

![kuva](https://user-images.githubusercontent.com/122886984/223061923-a5d79e2d-a1c0-490a-9d62-cb6be41bcf52.png)

Käynnistin Apachen uudelleen `sudo systemctl restart apache2`, jotta näkisin miten error.log reagoi. Se ei kuitenkaan onnistunut, vaan sain virheilmoituksen siitä, ettei uudelleenkäynnistystä suoritettu virheen takia. Tässä vaiheessa yhteys localhostiin kuitenkin katosi tyystin, ja sain Unable to connect - virheilmoituksen selaimessa. Error.log oli kuitenkin saanut täytettä:

    [Mon Mar 06 10:46:08.809798 2023] [mpm_event:notice] [pid 2992:tid 140045248970048] AH00491: caught SIGTERM, shutting down

Apache2 siis sulkeutui virheen vuoksi. Ratkaistessani tällaista bugia onneksi tuo configtest auttaisi ratkaisevasti vianselvityksessä, koska tuo error.log ei oikein sano mitään. Menin takaisin määrittelytiedostoon, ja korjasin muokkaamani tiedoston riviä 2 ottamalla piiloon kommentoidun määrittelyn takaisin käyttöön. Käynnistin Apachen uudeleen `sudo systemctl restart apache2`. Selaimella sivu ei lähtenyt heti toimimaan, Apache2-status muuttui saman tien aktiiviseksi. `curl localhost` tarjosi tuttua Not found -ilmoitusta, eli se toimi. Sitten huomasin, että selain kokeili jostain syystä https-linkkiä, jolloin liikenne ei suuntautudu 80-porttiin, vaan 443-porttiin, joka ei ole auki. Http-alulla kaikki toimi taas.

![kuva](https://user-images.githubusercontent.com/122886984/223068155-4249917d-79a8-4a1e-bd7a-716a342aa84e.png)

## e) Apachen WSGI-moduli puuttuu

Poistin Apachen WSGI-moduulin komennolla `sudo apt-get purge libapache2-mod-wsgi-py3`. Käynnistäessä uudelleen sain taas seuraavan virheilmoituksen:

    Job for apache2.service failed because the control process exited with error code.
    See "systemctl status apache2.service" and "journalctl -xe" for details.
    
Apache tosiaan oli sammunut, tämän huomasi myös selaimen kautta localhostiin yhdistäessä:

![kuva](https://user-images.githubusercontent.com/122886984/223071576-dc73bdf4-3dc0-42c5-8d88-eb81be369e0e.png)

Katsoin `sudo systemctl status apache2` komennolla Apachen statustietoja. Apache oli failed-tilassa:

![kuva](https://user-images.githubusercontent.com/122886984/223070743-404fb12c-e5eb-44e2-8a1b-2cfd1bfc3fa1.png)

Erityisen kiinnostava oli rivi:

    maalis 06 11:22:00 testarossa2 apachectl[3947]: Invalid command 'WSGIDaemonProcess', perhaps misspelled or defined by a module not in>

WSGI ei siis käynnisty, koska se on kirjoitettu väärin tai moduulia ei ole asennettu. Tämä on aika hyvä vinkki vianselvittäjälle ajaa wsgi-asennuskomento. Kävin katsomassa myös error.login. Siellä oli vain "caught SIGTERM, shutting down", mikä ei juuri auttanut. Asensin WSGI-moduulin uudestaan `sudo apt-get install libapache2-mod-wsgi-py3`. Käynnistin Apachen uudelleen. Status vaihtui jälleen aktiiviseksi, ja localhostiin tuli tuttu Not found ja adminiin pääsi myös.

## f) Väärät domain-nimet ALLOWED_HOSTS-kohdassa

Allowed_hostsia säädellään settings.py-tiedostossa, joten siirryin sinne `micro settings.py`. Otin hipsut localhostin ympäriltä ja kommentoin oikean määrittelyn talteen.

![kuva](https://user-images.githubusercontent.com/122886984/223074090-f630aa4c-eb81-4231-b2b0-2584056788a5.png)

Kosketin wsgi.py:tä `touch wsgi.py`, ja sain selaimesta localhostista ja localhost/administa vastaukseksi Internal server errorin.

![kuva](https://user-images.githubusercontent.com/122886984/223074636-f33488aa-eb68-43d9-941a-b0ea61cc03e2.png)

Apachen status oli aktiivinen. Error.log oli saanut runsaasti uutta sisältöä, ja kolme viimeistä ilmoitusta olivat varsin informatiivisia:

    [Mon Mar 06 11:45:07.486439 2023] [wsgi:error] [pid 4266:tid 140102833825536] [remote 127.0.0.1:41476]   File "/home/hanna/publicwsgi/hannapp/hannapp/settings.py", line 29, in <module>
    [Mon Mar 06 11:45:07.486450 2023] [wsgi:error] [pid 4266:tid 140102833825536] [remote 127.0.0.1:41476]     ALLOWED_HOSTS = [localhost]    #"localhost"
    [Mon Mar 06 11:45:07.486503 2023] [wsgi:error] [pid 4266:tid 140102833825536] [remote 127.0.0.1:41476] NameError: name 'localhost' is not defined

Ensimmäinen ilmoitus osoitti, että rivillä 29 settings.py:ssä on jotain häiriötä, ja se tulosti rivin sisällön seuraavaan ilmoitukseen. Viimeinen ilmoitus kertoi, ettei muuttujaa localhost ole määritelty. Tämän perusteella olisi vikatilanteessa varsin helppo suunnistaa settings.py-tiedostoon ja korjata virhe joko määrittelemällä muuttuja erikseen tai kirjoittamalla arvoksi suoraan "localhost". Sivusto lähti toimimaan selaimessa heti, kun olin vaihtanut settings.py:hyn lähtötilanteen mukaiset määritykset: 

![kuva](https://user-images.githubusercontent.com/122886984/223075989-68196035-17ed-4a20-83ed-ad1a263f3172.png)

Tehtävän tekeminen päättyy 11.55.

## Lähteet

- Chmod, 2021. Chmod. Wikipedia.org. https://fi.wikipedia.org/wiki/Chmod. Luettu 6.3.2023.
- Karvinen, T. 2023. Linux-palvelimet-kurssin luento 3.3.2023.
